Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$script:running = $false
$script:workerProcess = $null

function Append-Log {
  param([System.Windows.Forms.TextBox]$LogBox, [string]$Message)
  $timestamp = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')
  $LogBox.AppendText("[$timestamp] $Message`r`n")
}

function Read-EnvMap {
  param([string]$Path)
  $map = @{}
  if (Test-Path $Path) {
    foreach ($line in Get-Content $Path) {
      if ([string]::IsNullOrWhiteSpace($line) -or $line.Trim().StartsWith('#') -or -not $line.Contains('=')) { continue }
      $idx = $line.IndexOf('=')
      $key = $line.Substring(0, $idx).Trim()
      $value = $line.Substring($idx + 1)
      $map[$key] = $value
    }
  }
  return $map
}

function Write-EnvMap {
  param([string]$Path, [hashtable]$Map)
  $order = @(
    'MOCK_EBAY_MODE', 'EBAY_CLIENT_ID', 'EBAY_CLIENT_SECRET', 'EBAY_MARKETPLACE_ID',
    'EBAY_DELIVERY_COUNTRY', 'EBAY_DELIVERY_POSTAL_CODE', 'TELEGRAM_BOT_TOKEN',
    'TELEGRAM_CHAT_ID', 'DB_PATH', 'DATABASE_URL'
  )
  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add('# Generated by local wizard')
  foreach ($k in $order) {
    $v = ''
    if ($Map.ContainsKey($k)) { $v = [string]$Map[$k] }
    $lines.Add("$k=$v")
  }
  Set-Content -Path $Path -Value $lines -Encoding UTF8
}

function Invoke-Step {
  param(
    [System.Windows.Forms.TextBox]$LogBox,
    [string]$Label,
    [string]$Command
  )

  Append-Log $LogBox "$Label -> $Command"

  $psi = New-Object System.Diagnostics.ProcessStartInfo
  $psi.FileName = 'cmd.exe'
  $psi.Arguments = "/c $Command"
  $psi.RedirectStandardOutput = $true
  $psi.RedirectStandardError = $true
  $psi.UseShellExecute = $false
  $psi.CreateNoWindow = $true

  $proc = New-Object System.Diagnostics.Process
  $proc.StartInfo = $psi
  $null = $proc.Start()

  while (-not $proc.HasExited) {
    while (-not $proc.StandardOutput.EndOfStream) { Append-Log $LogBox ($proc.StandardOutput.ReadLine()) }
    while (-not $proc.StandardError.EndOfStream) { Append-Log $LogBox ($proc.StandardError.ReadLine()) }
    Start-Sleep -Milliseconds 100
    [System.Windows.Forms.Application]::DoEvents()
  }

  while (-not $proc.StandardOutput.EndOfStream) { Append-Log $LogBox ($proc.StandardOutput.ReadLine()) }
  while (-not $proc.StandardError.EndOfStream) { Append-Log $LogBox ($proc.StandardError.ReadLine()) }

  if ($proc.ExitCode -ne 0) {
    throw "Step failed ($Label), exit code: $($proc.ExitCode)"
  }
}

$form = New-Object System.Windows.Forms.Form
$form.Text = 'eBay Deal Finder - Local Control Center'
$form.Size = New-Object System.Drawing.Size(1100, 760)
$form.StartPosition = 'CenterScreen'

$title = New-Object System.Windows.Forms.Label
$title.Text = 'eBay Deal Finder - Local Control Center'
$title.Font = New-Object System.Drawing.Font('Segoe UI', 13, [System.Drawing.FontStyle]::Bold)
$title.AutoSize = $true
$title.Location = New-Object System.Drawing.Point(20, 15)
$form.Controls.Add($title)

$status = New-Object System.Windows.Forms.Label
$status.Text = 'Status: Idle'
$status.AutoSize = $true
$status.Location = New-Object System.Drawing.Point -ArgumentList 20, 45
$form.Controls.Add($status)

$configGroup = New-Object System.Windows.Forms.GroupBox
$configGroup.Text = 'Setup + .env Configuration'
$configGroup.Location = New-Object System.Drawing.Point(20, 70)
$configGroup.Size = New-Object System.Drawing.Size(500, 280)
$form.Controls.Add($configGroup)

$labels = @('Use mock mode', 'eBay Client ID', 'eBay Client Secret', 'Delivery ZIP', 'Telegram Bot Token', 'Telegram Chat ID')
$controls = @{}
for ($i = 0; $i -lt $labels.Count; $i++) {
  $lbl = New-Object System.Windows.Forms.Label
  $lbl.Text = $labels[$i]
  $lbl.AutoSize = $true
  $lbl.Location = New-Object System.Drawing.Point -ArgumentList 15, ([int](30 + ($i * 35)))
  $configGroup.Controls.Add($lbl)
}

$controls['MOCK_EBAY_MODE'] = New-Object System.Windows.Forms.CheckBox
$controls['MOCK_EBAY_MODE'].Location = New-Object System.Drawing.Point(160, 28)
$configGroup.Controls.Add($controls['MOCK_EBAY_MODE'])

function New-TextBoxAt([int]$y) {
  $tb = New-Object System.Windows.Forms.TextBox
  $tb.Location = New-Object System.Drawing.Point -ArgumentList 160, ([int]$y)
  $tb.Size = New-Object System.Drawing.Size(320, 24)
  return $tb
}

$controls['EBAY_CLIENT_ID'] = New-TextBoxAt 60
$controls['EBAY_CLIENT_SECRET'] = New-TextBoxAt 95
$controls['EBAY_DELIVERY_POSTAL_CODE'] = New-TextBoxAt 130
$controls['TELEGRAM_BOT_TOKEN'] = New-TextBoxAt 165
$controls['TELEGRAM_CHAT_ID'] = New-TextBoxAt 200

$controls['EBAY_CLIENT_SECRET'].UseSystemPasswordChar = $true

$configGroup.Controls.Add($controls['EBAY_CLIENT_ID'])
$configGroup.Controls.Add($controls['EBAY_CLIENT_SECRET'])
$configGroup.Controls.Add($controls['EBAY_DELIVERY_POSTAL_CODE'])
$configGroup.Controls.Add($controls['TELEGRAM_BOT_TOKEN'])
$configGroup.Controls.Add($controls['TELEGRAM_CHAT_ID'])

$saveEnvButton = New-Object System.Windows.Forms.Button
$saveEnvButton.Text = 'Save .env'
$saveEnvButton.Location = New-Object System.Drawing.Point(160, 235)
$saveEnvButton.Size = New-Object System.Drawing.Size(100, 30)
$configGroup.Controls.Add($saveEnvButton)

$setupButton = New-Object System.Windows.Forms.Button
$setupButton.Text = 'Run Setup Pipeline'
$setupButton.Location = New-Object System.Drawing.Point(275, 235)
$setupButton.Size = New-Object System.Drawing.Size(140, 30)
$configGroup.Controls.Add($setupButton)

$opsGroup = New-Object System.Windows.Forms.GroupBox
$opsGroup.Text = 'Bot Operations'
$opsGroup.Location = New-Object System.Drawing.Point(540, 70)
$opsGroup.Size = New-Object System.Drawing.Size(530, 280)
$form.Controls.Add($opsGroup)

$huntBtn = New-Object System.Windows.Forms.Button
$huntBtn.Text = 'Run Hunt Now'
$huntBtn.Location = New-Object System.Drawing.Point(20, 40)
$huntBtn.Size = New-Object System.Drawing.Size(150, 35)
$opsGroup.Controls.Add($huntBtn)

$scanBtn = New-Object System.Windows.Forms.Button
$scanBtn.Text = 'Run Scan Now'
$scanBtn.Location = New-Object System.Drawing.Point(190, 40)
$scanBtn.Size = New-Object System.Drawing.Size(150, 35)
$opsGroup.Controls.Add($scanBtn)

$workerStartBtn = New-Object System.Windows.Forms.Button
$workerStartBtn.Text = 'Start Worker'
$workerStartBtn.Location = New-Object System.Drawing.Point(360, 40)
$workerStartBtn.Size = New-Object System.Drawing.Size(140, 35)
$opsGroup.Controls.Add($workerStartBtn)

$workerStopBtn = New-Object System.Windows.Forms.Button
$workerStopBtn.Text = 'Stop Worker'
$workerStopBtn.Location = New-Object System.Drawing.Point(360, 85)
$workerStopBtn.Size = New-Object System.Drawing.Size(140, 35)
$opsGroup.Controls.Add($workerStopBtn)

$openDataBtn = New-Object System.Windows.Forms.Button
$openDataBtn.Text = 'Open Data Folder'
$openDataBtn.Location = New-Object System.Drawing.Point(20, 85)
$openDataBtn.Size = New-Object System.Drawing.Size(150, 35)
$opsGroup.Controls.Add($openDataBtn)

$opsInfo = New-Object System.Windows.Forms.Label
$opsInfo.Text = "Use Hunt/Scan buttons for manual runs or start worker for continuous scanning."
$opsInfo.Location = New-Object System.Drawing.Point(20, 140)
$opsInfo.Size = New-Object System.Drawing.Size(470, 50)
$opsGroup.Controls.Add($opsInfo)

$logBox = New-Object System.Windows.Forms.TextBox
$logBox.Multiline = $true
$logBox.ScrollBars = 'Vertical'
$logBox.ReadOnly = $true
$logBox.Font = New-Object System.Drawing.Font('Consolas', 9)
$logBox.Location = New-Object System.Drawing.Point(20, 370)
$logBox.Size = New-Object System.Drawing.Size(1050, 330)
$form.Controls.Add($logBox)

$envPath = '.env'
$envMap = Read-EnvMap $envPath
if ($envMap.Count -eq 0 -and (Test-Path '.env.example')) {
  Copy-Item '.env.example' '.env' -Force
  $envMap = Read-EnvMap $envPath
}

$controls['MOCK_EBAY_MODE'].Checked = (($envMap['MOCK_EBAY_MODE']) -eq '1')
$controls['EBAY_CLIENT_ID'].Text = [string]$envMap['EBAY_CLIENT_ID']
$controls['EBAY_CLIENT_SECRET'].Text = [string]$envMap['EBAY_CLIENT_SECRET']
$controls['EBAY_DELIVERY_POSTAL_CODE'].Text = [string]$envMap['EBAY_DELIVERY_POSTAL_CODE']
$controls['TELEGRAM_BOT_TOKEN'].Text = [string]$envMap['TELEGRAM_BOT_TOKEN']
$controls['TELEGRAM_CHAT_ID'].Text = [string]$envMap['TELEGRAM_CHAT_ID']

Append-Log $logBox 'Control Center ready.'
Append-Log $logBox 'Configure .env values on top-left, then run setup pipeline.'

$saveEnvButton.Add_Click({
  $map = Read-EnvMap $envPath
  $map['MOCK_EBAY_MODE'] = $(if ($controls['MOCK_EBAY_MODE'].Checked) { '1' } else { '0' })
  $map['EBAY_CLIENT_ID'] = $controls['EBAY_CLIENT_ID'].Text
  $map['EBAY_CLIENT_SECRET'] = $controls['EBAY_CLIENT_SECRET'].Text
  $map['EBAY_MARKETPLACE_ID'] = $(if ($map.ContainsKey('EBAY_MARKETPLACE_ID') -and $map['EBAY_MARKETPLACE_ID']) { $map['EBAY_MARKETPLACE_ID'] } else { 'EBAY_US' })
  $map['EBAY_DELIVERY_COUNTRY'] = $(if ($map.ContainsKey('EBAY_DELIVERY_COUNTRY') -and $map['EBAY_DELIVERY_COUNTRY']) { $map['EBAY_DELIVERY_COUNTRY'] } else { 'US' })
  $map['EBAY_DELIVERY_POSTAL_CODE'] = $controls['EBAY_DELIVERY_POSTAL_CODE'].Text
  $map['TELEGRAM_BOT_TOKEN'] = $controls['TELEGRAM_BOT_TOKEN'].Text
  $map['TELEGRAM_CHAT_ID'] = $controls['TELEGRAM_CHAT_ID'].Text
  $map['DB_PATH'] = $(if ($map.ContainsKey('DB_PATH') -and $map['DB_PATH']) { $map['DB_PATH'] } else { './data/dev.sqlite' })
  $map['DATABASE_URL'] = "file:$($map['DB_PATH'])"
  Write-EnvMap $envPath $map
  Append-Log $logBox '.env saved successfully.'
})

$setupButton.Add_Click({
  if ($script:running) { return }
  $script:running = $true
  $setupButton.Enabled = $false
  $status.Text = 'Status: Running setup...'

  try {
    $saveEnvButton.PerformClick()
    Invoke-Step $logBox 'Setup 1/4 Install dependencies' 'pnpm i'
    Invoke-Step $logBox 'Setup 2/4 Migrate DB' 'pnpm db:migrate'
    Invoke-Step $logBox 'Setup 3/4 Prisma generate' 'pnpm prisma:generate'
    Invoke-Step $logBox 'Setup 4/4 Typecheck' 'pnpm typecheck'
    $status.Text = 'Status: Setup complete'
    Append-Log $logBox 'Setup pipeline completed.'
  }
  catch {
    $status.Text = 'Status: Setup failed'
    Append-Log $logBox "ERROR: $($_.Exception.Message)"
  }
  finally {
    $setupButton.Enabled = $true
    $script:running = $false
  }
})

$huntBtn.Add_Click({ if (-not $script:running) { try { $script:running=$true; $status.Text='Status: Running hunt...'; Invoke-Step $logBox 'Manual Hunt' 'pnpm hunt:run'; $status.Text='Status: Idle' } catch { Append-Log $logBox "ERROR: $($_.Exception.Message)"; $status.Text='Status: Hunt failed' } finally { $script:running=$false } } })
$scanBtn.Add_Click({ if (-not $script:running) { try { $script:running=$true; $status.Text='Status: Running scan...'; Invoke-Step $logBox 'Manual Scan' 'pnpm scan:run'; $status.Text='Status: Idle' } catch { Append-Log $logBox "ERROR: $($_.Exception.Message)"; $status.Text='Status: Scan failed' } finally { $script:running=$false } } })

$workerStartBtn.Add_Click({
  if ($script:workerProcess -and -not $script:workerProcess.HasExited) {
    Append-Log $logBox 'Worker already running.'
    return
  }
  $psi = New-Object System.Diagnostics.ProcessStartInfo
  $psi.FileName = 'cmd.exe'
  $psi.Arguments = '/c pnpm worker:start'
  $psi.RedirectStandardOutput = $true
  $psi.RedirectStandardError = $true
  $psi.UseShellExecute = $false
  $psi.CreateNoWindow = $true

  $script:workerProcess = New-Object System.Diagnostics.Process
  $script:workerProcess.StartInfo = $psi
  $null = $script:workerProcess.Start()
  Append-Log $logBox 'Worker started.'

  $timer = New-Object System.Windows.Forms.Timer
  $timer.Interval = 500
  $timer.Add_Tick({
    if ($script:workerProcess -and -not $script:workerProcess.HasExited) {
      while (-not $script:workerProcess.StandardOutput.EndOfStream) { Append-Log $logBox ($script:workerProcess.StandardOutput.ReadLine()) }
      while (-not $script:workerProcess.StandardError.EndOfStream) { Append-Log $logBox ($script:workerProcess.StandardError.ReadLine()) }
    } else {
      Append-Log $logBox 'Worker exited.'
      $timer.Stop()
      $timer.Dispose()
    }
  })
  $timer.Start()
})

$workerStopBtn.Add_Click({
  if ($script:workerProcess -and -not $script:workerProcess.HasExited) {
    $script:workerProcess.Kill()
    Append-Log $logBox 'Worker stopped.'
  } else {
    Append-Log $logBox 'Worker is not running.'
  }
})

$openDataBtn.Add_Click({
  $dataPath = Join-Path (Get-Location) 'data'
  if (-not (Test-Path $dataPath)) { New-Item -ItemType Directory -Path $dataPath | Out-Null }
  Start-Process explorer.exe $dataPath
})

$form.Add_FormClosing({
  if ($script:workerProcess -and -not $script:workerProcess.HasExited) {
    try { $script:workerProcess.Kill() } catch {}
  }
})

[void]$form.ShowDialog()
